### ISSUE TITLE
XDR Operations types

### ISSUE THREAD

**Issue by juanhurtado10** [kommitters/stellar_base#49]
ℹ️ This issue is part of the Epic #8 

## Objective
To implement the XDR Operations types specified in https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x

## Checklist
- [x] Create account
- [x] Payment
- [x] Path payment strict receive
- [x] Manage sell offer
- [x] Create passive sell offer
- [x] Set options
- [x] Change trust
- [x] Allow trust
- [x] Account merge
- [x] Inflation
- [x] Manage data
- [x] Bump sequence
- [x] Manage buy offer
- [x] Path payment strict send
- [x] Create claimable balance
- [x] Claim claimable balance
- [x] Begin sponsoring future reserves
- [x] End sponsoring future reserves
- [x] Revoke sponsorship
- [x] Clawback
- [x] Clawback claimable balance
- [x] Set trust line flags
- [x] Liquidity pool deposit
- [x] Liquidity pool withdraw
